name: Pull Request Labels
on:
  pull_request:
    types: [opened,  reopened, labeled]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: exactly
          count: 1
          labels: "fips-checked"
          comment: "Aici gasesti cum sa pui label: https://github.com/cloudbees/docsite-engineering-cbci/blob/main/docs/modules/fips/pages/plugin-compliance-checklist.adoc"
