name: Pull Request Labels
on:
  pull_request:
    types: [opened,  reopened, labeled,  unlabeled]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          mode: minimum
          count: 1
          labels: "fips-checked, fips-exempt"
          comment: "bla bla"
            
