name: Pull Request Labels
on:
  pull_request:
    types: [opened,  reopened, labeled]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "fips-checked"
  do-other:
    runs-on: ubuntu-latest
    needs: label
    steps:
      - run: echo SUCCESS label is set
        if: needs.label.outputs.status == 'success'
      - run: echo FAILURE label not set && exit 1
        if: needs.label.outputs.status == 'failure'
